# Using php56 from ready image on docker hub
nginx:
  image: pseudecoder/centos-nginx
  volumes:
    - ./centos/config/nginx/sites:/etc/nginx/sites
    - ./app/php56/www:/var/www
  links:
    - php56
  ports:
    - 80:80
    - 443:443

php56:
  image: pseudecoder/centos-php56
  volumes:
    - ./centos/config/php56:/etc/php-fpm.d
    - ./app/php56/www:/var/www
  expose:
    - 9000
  links:
    - mongodb
    - redis

mongodb:
  image: pseudecoder/centos-mongodb
  volumes:
    - ./centos/config/mongodb/mongod.conf:/etc/mongod.conf
  ports:
    - 27017:27017
  expose:
    - 27017

redis:
  image: pseudecoder/centos-redis
  expose:
    - 6379
