# Using php56 from ready image on docker hub
nginx:
  container_name: myapp_nginx
  image: pseudecoder/centos-nginx
  volumes:
    - ./app/php56/container-config/nginx/sites-available:/etc/nginx/sites-available
    - ./app/php56/container-config/nginx/sites-enabled:/etc/nginx/sites-enabled
    - ./app/php56/www:/var/www
  links:
    - php56
  ports:
    - 80:80
    - 443:443

php56:
  container_name: myapp_php56
  image: pseudecoder/centos-php56
  volumes:
    - ./app/php56/www:/var/www
    - ./app/php56/container-config/php56:/etc/php-fpm.d
  expose:
    - 9000
  links:
    - mongodb
    - redis

mongodb:
  container_name: myapp_mongodb
  image: pseudecoder/centos-mongodb
  volumes:
    - ./app/php56/container-config/mongodb:/etc/mongodb
  ports:
    - 27017:27017
  expose:
    - 27017

redis:
  container_name: myapp_redis
  image: pseudecoder/centos-redis
  expose:
    - 6379
